### ISSUE TITLE
Error: spawn ETXTBSY

### ISSUE THREAD

**Issue by lukewaite** [browserstack/browserstack-local-nodejs#19]
I'm getting the following error when attempting to use this extension in CI.

```
Error: spawn ETXTBSY
    at exports._errnoException (util.js:893:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:367:9)
    at Object.exports.execFile (child_process.js:139:15)
    at /builds/intouch-capture/app/node_modules/browserstack-local/lib/Local.js:31:34
    at /builds/intouch-capture/app/node_modules/browserstack-local/lib/LocalBinary.js:44:11
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Is this possibly a race condition where the Binary is being executed while it is being moved into place?

**Comment by ChrisZieba** [comment]
Also seeing this issue

**Comment by eljefedelrodeodeljefe** [comment]
dito

**Comment by sankha93** [comment]
Are you on a Linux VM hosted on a Windows machine via Vagrant or something similar?

**Comment by lukewaite** [comment]
I'm inside a docker container running on Ubuntu 16.04.

**Comment by eljefedelrodeodeljefe** [comment]
For it is a CircleCI machine.

**Comment by ChrisZieba** [comment]
@sankha93 

This is the `circle.yaml` file I'm using, the container is running Ubuntu 14.04.

```yml
machine:
  node:
    version: 6.1.0
  services:
    - redis

dependencies:
  cache_directories:
     - mongodb-linux-x86_64-3.2.8
  pre:
    - if [[ ! -d mongodb-linux-x86_64-3.2.8 ]]; then wget http://downloads.mongodb.org/linux/mongodb-linux-x86_64-3.2.8.tgz && tar xvzf mongodb-linux-x86_64-3.2.8.tgz; fi
    - sudo /etc/init.d/mongod stop
    - sudo cp mongodb-linux-x86_64-3.2.8/bin/* /usr/bin
    - sudo /etc/init.d/mongod start

test:
  override:
    - NODE_ENV=test ./node_modules/cucumber/bin/cucumber.js ./client/test/features/hello-localize.feature
```

Here is the test it is running:

```js
'use strict';

const assert = require('cucumber-assert');
const config = require('config');
require('selenium-webdriver');

module.exports = function() {

  this.When(/^I open the homepage$/, function(next) {
    this.driver.get(`http://localhost:${config.ports.web}`);
    next();
  });

  this.Then(/^I should see "([^"]*)"$/, function(sourceMatch, next) {
    this.driver.getPageSource()
      .then(function(source) {
        assert.equal(source.indexOf(sourceMatch) > -1, true, next, 'Expected source to contain ' + sourceMatch);
      });
  });
};
```

and the feature file

```
Feature: Homepage testing

Scenario: Can check the homepage
When I open the homepage
Then I should see "Ready for the world?"
```
